### ISSUE TITLE
Option to not reset page numbering in post-content

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify#180]
Mischa was wondering whether we can just continue the numbering when going from body matter to  endnotes section.

Similar to https://github.com/joeha480/dotify/issues/165.

**Comment by joeha480** [comment]
pre-content and post-content are really artifacts of the physical volume. Currently, they are probably used for more things that they should be, due to the way the volume splitting works (which in turn have influenced the OBFL spec).

I am not sure it make sense to have pre-content and post-content interfere with the page flow. If you can put the end notes in the regular flow, then you should do that. If you're using dynamic-sequence (or a toc-sequence in case of #165), then it won't work.

I think allowing dynamic-sequences (and toc-sequence) in the regular flow makes more sense. Which we probably will be able to do once we redesign the volume splitting algorithm. Would that work, or are there additional use cases? Neither this issue or #165 really describes what the use case for this is, so the above is really me guessing.

**Comment by bertfrees** [comment]
It's really about content that belongs in pre-content and post-content:  things that are repeated in every volume such as title pages, and things that are presented per volume such as volume-range TOCs and volume endnotes. Allowing dynamic-sequence and toc-sequence in the regular flow would be a very nice feature but I don't think it would solve anything in these cases. Shall we discuss the use cases with the braille experts in one of our next calls?
