### ISSUE TITLE
Move temp file handling to FileJuggler

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/dotify#47]
```
Temp files are handled by FileJuggler (in org.daisy.util). However, when temp 
files are kept in Dotify, files are copied from the current temp file. This is 
somewhat ineffective. It would be better this was handled by FileJuggler. The 
current reuse of temp files would then be replaced with moving the file to a 
temp file directory if the files should be kept.

Adding the following constructor to FileJuggler:
FileJuggler(File pathToTemp, boolean keepFilesOnClose)

void writeTempFiles(boolean value)
boolean isWritingTempFiles()

Adding this to FileJuggler may be somewhat confusing as the "juggling" part is 
no longer used and swap() might have to be renamed. Therefore, creating another 
class building on this might be a better solution.
```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 26 Apr 2013 at 7:26

**Comment by joeha480** [comment]
In a file set context, file operations are optimized for the most common case: that resources from the input file set are included in the output file set. This can be achieved by moving them (assuming that they were originally copied into a temp folder. The issue of not copying debug files has a lower priority and since these two requirements are in direct conflict, this issue will not be fixed. In other words, copying files when this feature is turned on (for debugging) is better than always copying files in order to support moving files for debugging.
